apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-auth
spec:
  selector:
    matchLabels:
      run: main-auth
  replicas: 1
  template:
    metadata:
      labels:
        run: main-auth
    spec:
      containers:
      - name: main-auth
        image: localhost:5000/parasol-main-auth
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: main-auth
  labels:
    run: main-auth
spec:
  clusterIP: 10.233.40.4
  ports:
  - port: 8080
  selector:
    run: main-auth
