apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deposit
spec:
  selector:
    matchLabels:
      run: main-deposit
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10 
  strategy:
    rollingUpdate:
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        run: main-deposit
    spec:
      containers:
      - name: main-deposit
        image: localhost:5000/parasol-main-deposit:0.2-7
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: main-deposit
  labels:
    run: main-deposit
spec:
  clusterIP: 10.233.40.1
  ports:
  - port: 8080
  selector:
    run: main-deposit

