apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-account-balance
spec:
  selector:
    matchLabels:
      run: main-account-balance
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10 
  strategy:
    rollingUpdate:
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        run: main-account-balance
    spec:
      containers:
      - name: main-account-balance
        image: localhost:5000/parasol-main-account-balance:0.2-2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: main-account-balance
  labels:
    run: main-account-balance
spec:
  clusterIP: 10.233.40.7
  ports:
  - port: 8080
  selector:
    run: main-account-balance

