load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/82d96dcf75fdc3bac8b8934e97528b17496e6a7d.tar.gz",
    ],
    strip_prefix = "grpc-82d96dcf75fdc3bac8b8934e97528b17496e6a7d",
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()