FROM gradle:7.4.1-jdk11 as builder
WORKDIR /app
COPY . .
RUN gradle :application:core-application:build

FROM openjdk:11-jre-slim
COPY --from=builder /app/application/core-application/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]